apiVersion: v1
entries:
  ktharatt:
  - apiVersion: v2
    appVersion: beta-0.0.1
    created: "2025-07-20T20:08:39.790979+05:30"
    description: A Helm chart for Kubernetes Tharatt (Ktharatt)
    digest: ea57522badd1770e5f09b971aa84eebeda00880d6e7e9b3c5a229fe36754e07c
    name: ktharatt
    type: application
    urls:
    - https://riyasyash.github.io/ktharatt-charts/charts/ktharatt-0.1.0.tgz
    version: 0.1.0
generated: "2025-07-20T20:08:39.790164+05:30"
