apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ktharatt.operatorServiceAccountName" . }}
  labels:
    {{- include "ktharatt.labels" . | nindent 4 }}
  {{- with .Values.operatorServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ktharatt.workerServiceAccountName" . }}
  labels:
    {{- include "ktharatt.labels" . | nindent 4 }}
  {{- with .Values.workerServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ktharatt-operator
  namespace: default

---
# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ktharatt.operatorServiceAccountName" . }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [ "schedule.ktharatt.io" ]
    resources: [ "sleeps", "sleeps/status", "sleeps/finalizers" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ktharatt.operatorServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: ktharatt-operator
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ktharatt-operator
---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ktharatt.workerServiceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ktharatt.workerServiceAccountName" . }}
rules:
  - apiGroups: ["karpenter.sh"]
    resources: ["nodepools"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch", "update", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ktharatt.workerServiceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ktharatt.workerServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ktharatt.workerServiceAccountName" . }}
    namespace: default
